baseURL = 'https://digveer.com/'
languageCode = 'en-us'
title = 'Digveer'
disableKinds = ['taxonomy', 'term']
theme = 'hugo-book'

# Book theme specific configurations
[params]
  # Hide "Built with Hugo" footer
  BookPortableLinks = false
  # Disable search
  BookSearch = false
  # Disable table of contents
  BookToC = false
  # Disable section menu
  BookMenuBundle = false
  # Clean theme
  BookTheme = 'light'
